spring:
  # LIMIT FILE
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB
      resolve-lazily: true

  kafka:
    bootstrap-servers: 
    - optiplex3050.tailb8a972.ts.net:31773
    producer:
      retries: 2
      bootstrap-servers: 
      - optiplex3050.tailb8a972.ts.net:31773
  elasticsearch:
    uris:
    - http://optiplex3050.tailb8a972.ts.net:9200
      
# DOCUMENTATION
springdoc:
  api-docs:
    enabled: true
    path: /doc/api-docs
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html


# Management endpoint
management:
  endpoints.web.exposure.include: health,info,prometheus
  endpoint:
    health:
      access: READ_ONLY
    info:
      access: READ_ONLY

server:
  port: 8004
  error:
    whitelabel.enabled: false
    # include-exception: true
    # include-stacktrace: always
    # include-message: always
    # path: /error
  compression:
    enabled: true
    min-response-size: 4096
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
  tomcat.connection-timeout: 600000
  netty.connection-timeout: 600000
  forward-headers-strategy: native
